# Check https://circleci.com/docs/2.0/ for more details
# for config.yml syntax see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

orbs:
  # import Cypress orb by specifying an exact version x.y.z
  # or the latest version 1.x.x using "@1" syntax
  # https://github.com/cypress-io/circleci-orb
  cypress: cypress-io/cypress@1.27.0


commands:
  restore-cached-dependencies:
    description: restores the NPM cache and the cached Cypress binary
    steps:
      # Download and cache dependencies for the app and for tests
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
          # do not fall back to the previous cache
          # otherwise we will be "rolling over" previous Cypress binaries
          # adding newer versions until the cache is huge
          # we need "cypress cache prune" command

  install-dependencies:
    # Install NPM dependencies quickly using "npm ci"
    # https://on.cypress.io/continuous-integration
    # https://docs.npmjs.com/cli/ci
    description: installs npm dependencies
    steps:
      # Install NPM dependencies quickly
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Install TodoMVC dependencies
          command: npm ci
          working_directory: todomvc
      - run:
          name: Install TodoMVC Redux dependencies
          command: npm ci
          working_directory: todomvc-redux
      # show all installed Cypress versions
      - run: DEBUG=cypress:cli npx cypress cache path
      - run: DEBUG=cypress:cli npx cypress cache list
      - run:
          name: Verify cypress
          command: npx cypress verify

  cache-dependencies:
    description: Save NPM cache and Cypress binary
    steps:
      - save_cache:
          paths:
            # all NPM modules
            - ~/.npm
            # Cypress binary (or yarn dependencies)
            - ~/.cache
          key: dependencies-{{ checksum "package.json" }}

  store-test-artifacts:
    description: Saves Cypress screenshots and videos
    steps:
      - store_artifacts:
          path: cypress/screenshots
      - store_artifacts:
          path: cypress/videos

jobs:
  # example test job with 2 commands
  # 1. starts the app in the background
  # 2. runs the tests in a separate command
  two-commands:
    docker:
      # find Docker image at https://github.com/cypress-io/cypress-docker-images
      - image: cypress/base:12.14.0

    working_directory: ~/repo

    steps:
      - checkout
      - restore-cached-dependencies
      - install-dependencies
      - cache-dependencies

      - run:
          name: Run Cypress tests
          command: npm test

      - store-test-artifacts

workflows:
  version: 2
  tests:
    jobs:
      - two-commands

      # example jobs that use Cypress CircleCI Orb
      # see https://github.com/cypress-io/circleci-orb

      - cypress/install:
          name: install using orb
          executor: cypress/base-12-14-0

      # run tests on Firefox browser
      - cypress/run:
          store_artifacts: true
          record: true
          name: using Firefox
          executor: cypress/browsers-chrome78-ff70
          browser: firefox
          spec: 'cypress/integration/examples/actions.spec.js'
          no-workspace: true # since we don't need the workspace after this job

